default:
  image: ghcr.io/cirruslabs/flutter:latest
  cache:
    paths:
      - $CI_PROJECT_DIR/.pub-cache/
  before_script:
    - export PUB_CACHE=$CI_PROJECT_DIR/.pub-cache
    - export PATH="$PATH":"$PUB_CACHE/bin"
    - flutter --version
    - flutter pub get

stages:
  - test

lint_app:
  stage: test
  script:
    - cd app
    - dart format --output=none --set-exit-if-changed .
    - dart analyze

lint_core:
  stage: test
  script:
    - cd core
    - dart format --output=none --set-exit-if-changed .
    - dart analyze

test_app:
  stage: test
  script:
  - cd app
  - flutter test

test_core:
  stage: test
  script:
    - cd core
    - dart test
