name: vsd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  cristalyse: ^1.17.6
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  macos_ui: ^2.2.2
  multi_split_view: ^3.6.1
  pluto_grid: ^8.1.0
  shadcn_ui: ^0.54.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
